### ISSUE TITLE
UI: Schedule Page

### ISSUE THREAD

**Issue by IsaacMSchultz** [achieverapp/Achiever#11]
From team-project-drop-table created by [IsaacMSchultz](https://github.com/IsaacMSchultz): CptS-489-WSU/team-project-drop-table#9  

# Tasks
- [x] Implement visual style for tasks that have been blocked at a given time.
  - [x] Style the task using the CSS styles for priority.
- [x] Query mock-model for tasks to populate the list.

# Create Time Block Modal
- [x] Drop-down to select a specific uncompleted task.
  * something to keep in mind: A search bar to possibly narrow down the list of tasks??? We only expect for more tasks to get added over time and it may become difficult to scroll through a list of 10+ tasks
- [x] start and end time selectors
  - [x] should be populated with the time selected if the user clicks on an empty part of the schedule.
  - [x] Should implement error checking to ensure a user cannot schedule multiple tasks at the same time
    * Or do??? This might be some unique functionality but implementing this visually may be difficult.

# Things to think about
We spoke about creating tasks that can be scheduled to re-occur on specific days/weeks etc... We may want to implement a way to do the same with time block scheduling for a larger task.
