### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by IsaacMSchultz** [achieverapp/Achiever#14]
From team-project-drop-table created by [IsaacMSchultz](https://github.com/IsaacMSchultz): CptS-489-WSU/team-project-drop-table#13  

# MongoDB database
The following RESTful API functionalities will be built on a local mongoDB database for now.

# User
Begin implementing CRUD for user objects.
- [x] Create
- [x] Receive
- [x] Update
- [x] Delete

A User Object should include:
  - [x] Saved tasks (templates)
  - [x] In progress tasks
  - [x] Completed tasks
  - [x] User information
    - [x] Name
    - [x] Id

# Task
Begin implementing just Create and Read for a task.
- [x] Create
- [x] Read

A task should include:
  - [x] Task name
  - [x] Category
  - [x] Priority
  - [x] Subtasks
  - [x] Scheduled time block
    - [x] start
    - [x] end
  - [x] Due date
  - [x] Completion date
