### ISSUE TITLE
UI: Mobile Optimizations

### ISSUE THREAD

**Issue by IsaacMSchultz** [achieverapp/Achiever#23]
From team-project-drop-table created by [IsaacMSchultz](https://github.com/IsaacMSchultz): CptS-489-WSU/team-project-drop-table#10  

# Navbar
- [x] dynamically switch to a hamburger menu when the display is too small to show all nav items in one row.
  - [x] Menu slides down from the top of the screen.

# Task List Page
- [x] Re-confiure create new task button so that it is floating in the bottom right.

# Task View/Edit Page
 - [x] Footer containing drop-downs and date/time inputs should become multi-row when the devices screen is not large enough to fit them all on one line.

# General
- [x] Unify padding and margin spacing across all pages.
